#!/bin/bash
#
# Lints all javascript files for the current project.
#
# - Install NodeJS
#   http://nodejs.org/download/
#
# - Install jshint cli (-g for globally)
#   $ sudo npm install jshint -g
#
# - Configure options
#   $ vi batch/tools/jshint/jshint.conf.json
#

LINT_FILES=`find web/revtk -name '*.js'`
LINT_FILES="$LINT_FILES `find lib/front/corejs -name '*.js'`"
LINT_FILES="$LINT_FILES `find lib/front/revtk -name '*.js'`"

# JsHint config file in json format, see http://jshint.com/docs/
JSHINT_OPTS=batch/tools/jshint/jshint.conf.json

#for FOO in `git diff HEAD --name-only | grep '.js$'`; do

echo 'Linting Javascript files...'

for FILE_TO_LINT in $LINT_FILES ; do

  # Ignore temporary files that I prefix with "__"
  if [[ $FILE_TO_LINT =~ '__' ]] ; then continue ; fi

  # Ignore pre-packed files from third party libraries
  if [[ $FILE_TO_LINT == *.pack.js ]] ; then continue; fi

  # Skip file with BOM mark that chokes jslint (NOTE: fonctionne avec jshint!)
  #if [[ $FILE_TO_LINT =~ web/revtk/study/keywords-rt[hk].js ]] ; then continue ; fi

  echo JSHint ... $FILE_TO_LINT

  jshint --config=$JSHINT_OPTS "${FILE_TO_LINT}"

  # Break if file does not lint
  RETVAL=$?
  if (( $RETVAL )) ; then
    echo " ERROR: JSHint failed on:  $FILE_TO_LINT"
    exit 1
  fi
done

